version: '3.8'

services:
  postgres:
    container_name: nestjs-boilerplate-postgres
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: nestjs-boilerplate
      POSTGRES_PASSWORD: nestjs-boilerplate
      POSTGRES_DB: nestjs-boilerplate_db
    volumes:
      - nestjs_boilerplate_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  nestjs_boilerplate_pg_data:
