version: '3.8'

services:
  postgres:
    container_name: nestjs-boilerplate
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: nestjs-boilerplate
      POSTGRES_PASSWORD: nestjs-boilerplate
      POSTGRES_DB: nestjs-boilerplate_db
    volumes:
      - polls_pg_data:/bitnami/postgresql
